# ===== 文件导读 =====
# [职责] 包的门面：把这个包里值得对外用的名字，一次性搬到 hello_agents.tools 这一层。
#        于是外面可以写 from hello_agents.tools import Tool，而不用写 from ...base import Tool。
# [位置] 顶层。任何 import hello_agents.tools.xxx 的动作都会先执行这个文件（下面有实测）。
# [阅读顺序] ① 前几行的分块导入（每块一个注释标题）
#            → ② __all__（它到底管什么、不管什么）
#            → ③ 回到开头，看包导入的时机与代价。
# [本文件新概念] ① 包的 __init__.py 何时执行　② 导入子模块会先执行所有父包
#                ③ __all__ 只影响 import *　④ 显式相对导入 vs 绝对导入　⑤ 「慷慨导出」的代价。
# [实测] 导入本包的代价约 2.2 秒，而且不管你导多深都一样：
#        import hello_agents                          2.22s
#        import hello_agents.tools                    2.27s
#        import hello_agents.tools.base               2.19s
#        import hello_agents.tools.builtin.win_rate_tool  2.17s
# ===================
"""工具系统"""

# [语法] 相对导入（开头那个点 = 当前这个包）。这里只挑两个名字搬上来：
#        基类和参数说明 —— 写自定义工具只需要这两个。
# [概念] 注意 tool_action 和 AutoGeneratedTool **没有**被搬上来，
#        想用装饰器必须写 from hello_agents.tools.base import tool_action —— 多绕一层。
from .base import Tool, ToolParameter
from .registry import ToolRegistry, global_registry

# [概念] ★ 包导入的时机：这一行（以及下面每一行）都在**模块第一次被导入时**执行，
#        之后 Python 把它缓存进 sys.modules，再 import 就直接拿缓存，不会重跑。
# [机制] 所以这个文件其实是「包的门面 + 一份导入清单」，它在被任何人使用之前就已经跑完了。
# [易错] 反过来说：这里写的任何导入都会**无条件**发生。哪怕你只想用 registry，
#        下面这些统统会被拖进来（含它们的第三方依赖）—— 代价见文件末尾的实测。
# 内置工具
from .builtin.search_tool import SearchTool
from .builtin.calculator import CalculatorTool
from .builtin.memory_tool import MemoryTool
from .builtin.rag_tool import RAGTool
from .builtin.note_tool import NoteTool
from .builtin.terminal_tool import TerminalTool

# [概念] 按「知识块」分组的导入。MCP / A2A / ANP 都是 Agent 之间的通信协议，
#        它们是独立的一章，却被塞进了每次导入都要付钱的位置。
# 协议工具
from .builtin.protocol_tools import MCPTool, A2ATool, ANPTool

# [概念] 这四个是「评测 Agent 表现」用的工具（BFCL 基准、GAIA 基准、LLM 打分、胜率对比）。
# [为什么] 它们属于课程第 12 章的内容，和「工具系统」本身没什么关系，
#        但因为放在同一个包目录下，就被一并导出了。包的分层和章节的分层并不一致。
# 评估工具（第12章）
from .builtin.bfcl_evaluation_tool import BFCLEvaluationTool
from .builtin.gaia_evaluation_tool import GAIAEvaluationTool
from .builtin.llm_judge_tool import LLMJudgeTool
from .builtin.win_rate_tool import WinRateTool

# [概念] 同上：这是第 11 章强化学习用的工具，也挂在 tools 包下。
# RL训练工具（第11章）
from .builtin.rl_training_tool import RLTrainingTool

# [概念] 工具链和异步执行器 —— 前面两轮读过的那两个文件。它们在这里只是被导出，
#        实际没有任何 Agent 使用；而且 async_executor 的导出函数实测一调就抛 TypeError。
# [易错] 「导出成功」和「能用」是两回事：from hello_agents.tools import run_parallel_tools
#        这句话本身毫无问题，问题要到调用时才出现。
# 高级功能
from .chain import ToolChain, ToolChainManager, create_research_chain, create_simple_chain
from .async_executor import AsyncToolExecutor, run_parallel_tools, run_batch_tool, run_parallel_tools_sync, run_batch_tool_sync

# [概念] ★ __all__ 是一个普通列表，它**只影响一件事**：from hello_agents.tools import * 时导哪些名字。
# [易错] 它不管这些：
#        · 不影响 import hello_agents.tools 能否成功
#        · 不影响 from hello_agents.tools import Tool（显式指名不受 __all__ 限制）
#        · 不做任何访问控制，没列进来的名字照样能被 import 到
# [为什么] 所以它主要是「这是本包的公开 API」的一份声明，给人看、也给 IDE 和文档工具看。
__all__ = [
    # 基础工具系统
    "Tool",
    "ToolParameter",
    "ToolRegistry",
    "global_registry",

    # [概念] __all__ 里也用注释分了组，和上面的导入一一对应 —— 两处必须同步维护。
    # [易错] 这种「同一份信息写两遍」的结构容易走样：加了新工具忘了往 __all__ 里加，
    #        import * 就会漏掉它，而且不会有任何报错。
    # 内置工具
    "SearchTool",
    "CalculatorTool",
    "MemoryTool",
    "RAGTool",
    "NoteTool",
    "TerminalTool",

    # 协议工具
    "MCPTool",
    "A2ATool",
    "ANPTool",

    # 评估工具
    "BFCLEvaluationTool",
    "GAIAEvaluationTool",
    "LLMJudgeTool",
    "WinRateTool",

    # RL训练工具
    "RLTrainingTool",

    # [易错] 注意这里列了 ToolChain / ToolChainManager / create_* 四个名字，
    #        但**没有列 AsyncToolExecutor 之外的 run_*_sync 那几个**（它们在下面单独一组）。
    #        分组标准并不统一，读的时候别把「在 __all__ 里」当成「更正式 / 更可靠」。
    # 工具链功能
    "ToolChain",
    "ToolChainManager",
    "create_research_chain",
    "create_simple_chain",

    # 异步执行功能
    "AsyncToolExecutor",
    "run_parallel_tools",
    "run_batch_tool",
    "run_parallel_tools_sync",
    "run_batch_tool_sync",
]
