# ===== 文件导读 =====
# [职责] 工具系统的地基：定义「什么是一个工具」（Tool 抽象基类）和「怎么把普通方法变成工具」（@tool_action）。
# [位置] tools/ 包的根。registry.py 导入 Tool 才能存工具；agents/*.py 导入它来注册工具；
#        tools/builtin/*.py 全部继承它。上层（Agent）只认 run / get_parameters 两个方法。
# [阅读顺序] ① tool_action 装饰器 —— 怎么给方法贴标签
#            → ② Tool 抽象基类 —— 工具的契约；get_expanded_tools 是自动发现标签的地方
#            → ③ AutoGeneratedTool —— 把「一个方法」包装成「一个工具」。
# [本文件新概念] ① 装饰器工厂　② 继承与 super　③ 委托（组合）　④ 运行时内省 inspect　⑤ 类型转换表。
# ===================
"""工具基类"""

# [语法] 下面的导入分三类：abc / typing 是标准库，pydantic 是第三方库，
#        from .base import Tool 那种带点的（在别的文件里）才是包内相对导入。
# [概念] 注意 typing 里的 get_type_hints —— 它是「把注解还原成真正的类型对象」的工具，
#        AutoGeneratedTool._parse_parameters 里会用到它。没有它就读不出 -> str 这种写在签名里的类型。
from abc import ABC, abstractmethod
from typing import Dict, Any, List, Optional, Callable, get_type_hints
from pydantic import BaseModel
import inspect
import re


# [作用] 装饰器工厂：给方法贴上三个私藏标记（_is_tool_action / _tool_name / _tool_description），
#        供 Tool.get_expanded_tools() 在运行时扫描发现。
# [参数] name / description 都可以省略（默认 None = 「以后从方法名和 docstring 推」）。
# [返回] decorator —— 注意它返回的不是结果，而是「另一个函数」。这正是本文件第一个新概念。
# [易错] 它不改变方法的行为，只是在函数对象上挂了几个属性；方法本身照常被调用。
def tool_action(name: str = None, description: str = None):
    """装饰器：标记一个方法为可展开的工具 action

    用法:
        @tool_action("memory_add", "添加新记忆")
        def _add_memory(self, content: str, importance: float = 0.5) -> str:
            '''添加记忆

            Args:
                content: 记忆内容
                importance: 重要性分数
            '''
            ...

    Args:
        name: 工具名称（如果不提供，从方法名自动生成）
        description: 工具描述（如果不提供，从 docstring 提取）
    """
    # [概念] 装饰器工厂 = 两层函数。外层 tool_action(name, description) 先收「配置」，
    #        返回内层 decorator；内层再收「被装饰的函数 func」，加工完把它还回去。
    # [语法] 为什么要分两层？因为实际写法 @tool_action("memory_add", "添加新记忆") 是**带括号**的：
    #        带括号就先执行外层、拿到 decorator，Python 再把下面的函数交给它。等价于：
    #            _add_memory = tool_action("memory_add", "添加新记忆")(_add_memory)
    # [机制] 这套写法能成立的前提是「Python 里函数也是对象」：
    #        函数可以被赋值、被传参、被返回，也可以像下面这样被挂上属性。
    def decorator(func: Callable):
        # [机制] 在函数对象上写三个自定义属性（Python 允许这么做：函数本质是普通对象，
        #        这些临时属性存在它的 __dict__ 里）。这三行就是「贴标签」的全部动作。
        # [为什么] 用挂属性，而不是维护一份全局名单：标签跟着函数走 ——
        #        谁定义了工具，信息就在谁身上，不怕函数被传来传去，也不用额外注册表。
        func._is_tool_action = True
        func._tool_name = name
        func._tool_description = description
        # [语法] 把原函数原样返回 —— 所以装饰之后方法还是原来那个方法，只是多了三个属性。
        #        如果这里返回的是别的函数，原方法就被替换掉了（那才是「包装」型装饰器）。
        return func
    # [语法] 外层返回内层。执行到这一行时，被装饰的函数还没出现 —— 那是装饰时机的下一拍。
    return decorator


# [作用] 单个参数的「说明书」：名字、类型、说明、是否必填、默认值。
# [概念] 它继承 Pydantic 的 BaseModel，所以这 5 行字段声明自带构造、校验和 .dict() 转换。
#        不用手写 __init__，也不用自己记字段顺序 —— 调用时用关键字传参即可。
# [易错] type 存的是字符串而不是 Python 类型对象：因为它最终要变成 JSON Schema 里的
#        "string" / "integer" 这些词，发给模型看。
class ToolParameter(BaseModel):
    """工具参数定义"""
    name: str
    type: str
    description: str
    required: bool = True
    default: Any = None


# [作用] 工具的抽象基类：规定所有工具都必须能 run（执行）和 get_parameters（说明自己要什么参数）。
# [概念] 这是「继承 + 抽象方法」的标准用法：子类补上这两个方法就能用，重复的样板代码不用写；
#        而 registry 只认这两个方法，所以任何子类都能被一视同仁地调用 —— 这就是多态。
# [为什么] 用 ABC 而不是普通类：把「必须实现 run 和 get_parameters」从口头约定变成强制约束，
#        漏实现的话实例化当场抛 TypeError（强制机制详见 core/agent.py 的注释）。
# [概念] 本类还带来一个新玩法叫「可展开工具」：一个类里写了多个动作时，
#        不必手动拆成多个类 —— 贴了 @tool_action 的方法会被自动发现、自动包装成一个个独立工具。
class Tool(ABC):
    """工具基类

    支持两种使用模式：
    1. 普通模式：工具作为单一实体使用
    2. 可展开模式：工具可以展开为多个独立的子工具（每个子工具对应一个功能）

    展开模式支持两种实现方式：
    - 手动定义子工具类（传统方式）
    - 使用 @tool_action 装饰器自动生成（推荐）
    """

    # [作用] 存下三个最基本的属性（名字、描述、是否可展开）。
    # [易错] 这里没有调用 super().__init__() —— 因为 Tool 的直接父类是 ABC，
    #        而 ABC 的 __init__ 就是 object.__init__，什么都不做，省掉这行不会出错。
    #        但如果哪天换成一个真正有状态的父类，就**必须**补上 super().__init__(...)。
    def __init__(self, name: str, description: str, expandable: bool = False):
        """初始化工具

        Args:
            name: 工具名称
            description: 工具描述
            expandable: 是否可展开为多个子工具
        """
        self.name = name
        self.description = description
        self.expandable = expandable

    # [作用] 声明「子类必须实现」的执行入口。注意方法体只有 pass —— 抽象方法不提供实现。
    # [概念] run 收一个 dict（参数名 → 参数值），返回字符串。
    #        用 dict 而不是具名参数，是为了让参数五花八门的各种工具共享同一个调用入口。
    @abstractmethod
    def run(self, parameters: Dict[str, Any]) -> str:
        """执行工具"""
        pass

    # [作用] 声明「子类必须实现」的参数说明书出口。返回的是一串 ToolParameter。
    @abstractmethod
    def get_parameters(self) -> List[ToolParameter]:
        """获取工具参数定义"""
        pass

    # [作用] 把「一个工具对象」展开成「一批子工具」。默认实现就是：
    #        扫描自己身上贴了 @tool_action 标签的方法，每个包装成一个 AutoGeneratedTool。
    # [返回] 可展开且找到了标签方法 → 子工具列表；否则 None（表示「我就是个普通工具」）。
    # [概念] 委托 + 组合：AutoGeneratedTool 拿到 self（父工具）和方法本身，而不是复制粘贴代码 ——
    #        子工具只负责「翻译参数」，真正的活还是父对象上那个方法干的。
    # [实测] 这也解释了 builtin 里为什么一个类能贡献出二十多个工具名。
    def get_expanded_tools(self) -> Optional[List['Tool']]:
        """获取展开后的子工具列表

        默认实现：自动从标记了 @tool_action 的方法生成子工具
        子类可以重写此方法提供自定义的展开逻辑

        Returns:
            如果工具支持展开，返回子工具列表；否则返回 None
        """
        # [机制] 第一道闸门：不是可展开工具就直接返回 None，连扫描都省了。
        if not self.expandable:
            return None

        # 自动从装饰器标记的方法生成工具
        # [机制] inspect.getmembers(self, predicate=inspect.ismethod) 的意思是：
        #        在运行时把实例身上所有「绑定方法」列成 (名字, 方法) 的列表。
        #        这一步没有任何魔法 —— 装饰器当初把标签挂在函数上，这里再顺着实例把它们找回来。
        # [概念] 内省（introspection）：程序在运行时查看自己的结构。
        #        整个「自动生成参数说明」的能力都建立在它之上；没有它就只能手写 get_parameters。
        tools = []
        # [语法] 遍历时用两个变量解包 (名字, 方法) 这个元组。
        # [易错] 循环变量 name 其实**没被用到**：工具名取自装饰器标签 method._tool_name。
        #        它写在这里只是为了让元组解包对得上，别被它带偏。
        for name, method in inspect.getmembers(self, predicate=inspect.ismethod):
            # [概念] 鸭子类型：不检查「它是不是某个类的实例」，只检查「它身上有没有这个属性」。
            #        装饰器留下的 _is_tool_action 就是这里的唯一凭据。
            if hasattr(method, '_is_tool_action'):
                # [概念] 三个参数里 parent=self 是关键：子工具并不认识 self 的方法体，
                #        它只是把调用转交回父对象 —— 这叫委托（delegation），比继承更松的复用方式。
                tool = AutoGeneratedTool(
                    parent=self,
                    method=method,
                    name=method._tool_name,
                    description=method._tool_description
                )
                tools.append(tool)

        # [语法] 条件表达式（三元）：A if 条件 else B。
        #        这里等于「找到标签方法就返回列表，一个都没有就返回 None」。
        # [为什么] 返回 None 而不是空列表：让上层用一句 if expanded_tools: 同时挡住两种情况。
        return tools if tools else None

    # [作用] 最朴素的参数校验：只看「必填项是不是都给了」，不查类型、不管多余键。
    # [语法] 列表推导式 [p.name for p in ... if p.required]：先筛掉非必填，再取名字。
    # [语法] all(生成器) = 全部为真才返回 True，碰到第一个假就短路。
    # [易错] 空列表时 all([]) 返回 True —— 所以「没有必填参数」的工具永远校验通过。
    def validate_parameters(self, parameters: Dict[str, Any]) -> bool:
        """验证参数"""
        required_params = [p.name for p in self.get_parameters() if p.required]
        return all(param in parameters for param in required_params)

    # [作用] 转成给提示词用的普通字典。
    # [易错] param.dict() 是 Pydantic v1 的老写法，v2 里已标记废弃（正确写法是 model_dump()）。
    #        现在还能跑，但会有告警；同一个文件里两种风格混着，属于历史遗留。
    def to_dict(self) -> Dict[str, Any]:
        """转换为字典格式"""
        return {
            "name": self.name,
            "description": self.description,
            "parameters": [param.dict() for param in self.get_parameters()]
        }

    # [作用] 把工具翻译成 OpenAI function calling 要求的 JSON Schema —— 即给模型看的「函数签名」。
    # [概念] 同一个工具要输出两种格式：to_dict() 给「文本协议」的提示词用，
    #        本方法给「原生 function calling」用（FunctionCallAgent 走这条路）。
    # [为什么] 要转换而不能直接用：OpenAI 的 schema 只认 JSON 那几种类型名，
    #        而且它没有 default 字段 —— 所以下面只能把默认值「塞进描述文字里」。
    def to_openai_schema(self) -> Dict[str, Any]:
        """转换为 OpenAI function calling schema 格式

        用于 FunctionCallAgent，使工具能够被 OpenAI 原生 function calling 使用

        Returns:
            符合 OpenAI function calling 标准的 schema
        """
        parameters = self.get_parameters()

        # 构建 properties
        # [语法] 用两个局部变量一边遍历一边攒结果：
        #        properties 是「参数名 → 定义」的字典，required 是「必填参数名」的列表。
        #        字典从 Python 3.7 起保证插入顺序，所以参数顺序是稳定的。
        properties = {}
        required = []

        for param in parameters:
            # 基础属性定义
            # [概念] 每个参数在 JSON Schema 里长这样：{"type": "string", "description": "..."}。
            #        type 用的是 "string"/"integer"/"array" 这类 JSON 类型名，不是 Python 的 str/int/list。
            prop = {
                "type": param.type,
                "description": param.description
            }

            # 如果有默认值，添加到描述中（OpenAI schema 不支持 default 字段）
            # [易错] 这里把默认值拼进了描述字符串。两个副作用：
            #        ① 模型只能「读到」默认值，并不能真的省略这个参数；
            #        ② 若默认值本身就是 None，这里判断不出来，会被当成「没有默认值」漏掉。
            if param.default is not None:
                prop["description"] = f"{param.description} (默认: {param.default})"

            # 如果是数组类型，添加 items 定义
            # [易错] 数组类型一律写成「字符串数组」，因为 ToolParameter 里没地方描述元素类型。
            #        需要整数数组的工具走这条路，模型会填成字符串，一直要到实现里才炸。
            if param.type == "array":
                prop["items"] = {"type": "string"}  # 默认字符串数组

            properties[param.name] = prop

            # 收集必需参数
            if param.required:
                required.append(param.name)

        # [语法] 返回的是嵌套字典：最外层固定 "type": "function"，
        #        里面 "function" 才是名字 / 描述 / 参数三件套。这个形状由 OpenAI 规定，不能改。
        return {
            "type": "function",
            "function": {
                "name": self.name,
                "description": self.description,
                "parameters": {
                    "type": "object",
                    "properties": properties,
                    "required": required
                }
            }
        }

    # [作用] 决定 print(工具对象) 和调试时看到什么。
    # [概念] __str__ 管「给人看」，__repr__ 管「给开发者看 / 在列表里显示」。
    #        这里 __repr__ 直接复用 __str__，所以两种场合输出完全一致。
    # [易错] 不重写的话，print 出来是 <hello_agents.tools.base.Tool object at 0x...> 一排地址，
    #        调试工具系统时根本看不出是哪个工具。
    def __str__(self) -> str:
        return f"Tool(name={self.name})"

    def __repr__(self) -> str:
        return self.__str__()


# [作用] 把「父工具身上的一个方法」包装成一个独立、可注册的工具。
# [概念] 这里同时用了两个复用手段：
#        继承 —— 它继承 Tool，所以能像别的工具一样被 registry 存起来、统一调用；
#        委托 —— 它自己不算数，真正干活的是 self.parent 上的 self.method。
# [为什么] 两个一起用：继承解决「能不能被系统当作工具」，委托解决「活由谁干」。
#        这也是设计里常说的那句「继承用于类型，组合用于行为」。
# [实测] inspect.signature + get_type_hints 一起用，才知道方法要哪些参数、什么类型、
#        有没有默认值 —— 这是「不用手写参数说明」的全部底气。
class AutoGeneratedTool(Tool):
    """自动生成的工具 - 从方法签名和 docstring 自动提取参数"""

    # [作用] 先存好委托对象（parent / method），再推出工具名和描述，最后交给父类 Tool 存属性。
    # [易错] self.parent / self.method 必须在 super().__init__() **之前**赋值，
    #        因为下面两句会立刻用到它们；反过来，self.name 要等父类跑完才存在。
    # [概念] 这个「先自己后父类」的顺序不是风格问题，是被依赖关系逼出来的。
    def __init__(self, parent: Tool, method: Callable, name: str = None, description: str = None):
        """初始化自动生成的工具

        Args:
            parent: 父工具实例
            method: 被装饰的方法
            name: 工具名称（如果为 None，从方法名生成）
            description: 工具描述（如果为 None，从 docstring 提取）
        """
        self.parent = parent
        self.method = method

        # 生成工具名称
        # [机制] 工具名从「父工具名 + 方法名（去掉前导下划线）」拼出来。
        #        例：MemoryTool(expandable=True) 里的 _add_memory → memory_add。
        # [语法] lstrip('_') 去掉左侧所有下划线 —— 注意它和 removeprefix('_') 不同，会一次全删。
        if name is None:
            # 从方法名生成：_add_memory -> parent_name_add_memory
            method_name = method.__name__.lstrip('_')
            name = f"{parent.name}_{method_name}"

        # 提取描述
        if description is None:
            # [机制] 没给描述就去问 docstring —— 又是内省。
            #        这类「能推就推、推不出来才兜底」的写法贯穿全文件，也解释了它对注释格式的强依赖。
            description = self._extract_description_from_docstring()

        # [语法] super() = 「按方法解析顺序找到的父类」，这里就是 Tool。
        #        参数用关键字传（name=... / description=...），省得去记位置。
        super().__init__(name=name, description=description)

        # 自动解析参数
        # [概念] 参数在**构造时**就解析好，存进 self._parameters；
        #        之后 get_parameters() 只是把它取出来。属「算一次、用多次」的缓存思路。
        self._parameters = self._parse_parameters()

    # [作用] 没显式给描述时，从方法 docstring 里挑第一行像人话的作为工具描述。
    # [易错] 它只看第一个合格的行，并且会跳过以 Args: / Returns: 开头的行 ——
    #        等于要求「docstring 第一行必须是摘要」。顺序写反了，描述就会变成一串参数名。
    def _extract_description_from_docstring(self) -> str:
        """从 docstring 提取描述"""
        doc = inspect.getdoc(self.method)
        if not doc:
            return f"执行 {self.method.__name__}"

        # 提取第一行作为描述
        lines = doc.split('\n')
        # [语法] 用 for 而不是直接取 lines[0]：因为要跳过空行和 Args: 行，一直找到第一个合格的行。
        # [易错] 这里用 doc.split('\n') 而不是 splitlines()，对 \r 的处理会比较糙。
        for line in lines:
            line = line.strip()
            if line and not line.startswith('Args:') and not line.startswith('Returns:'):
                return line

        return f"执行 {self.method.__name__}"

    # [作用] 本文件的核心：靠内省从方法签名 + docstring 推断出参数说明书。
    # [机制] 三个数据源分工明确：
    #        ① inspect.signature → 有哪些参数、谁有默认值；
    #        ② get_type_hints     → 参数注解（把字符串形式的注解还原成真正的类型对象）；
    #        ③ inspect.getdoc     → 参数的文字说明。
    # [易错] 三者都是「尽力而为」：注解没写就当 str，docstring 没写 Args: 就退化成「参数 xxx」，
    #        全程不报错 —— 静默降级正是这类自动机制最难查的地方。
    def _parse_parameters(self) -> List[ToolParameter]:
        """从方法签名和 docstring 自动提取参数"""
        sig = inspect.signature(self.method)
        type_hints = get_type_hints(self.method)
        docstring = inspect.getdoc(self.method) or ""

        # 从 docstring 解析参数描述
        param_descriptions = self._parse_param_descriptions(docstring)

        parameters = []
        # [语法] sig.parameters 是个有序映射，遍历它拿到的是 (参数名, Parameter 对象)。
        # [易错] 下一行 type_hints.get(param_name, str) 的默认值 str 意味着「没写注解 = 字符串」。
        #        于是本该是整数的参数一旦忘了写注解，就会被当成文本发给模型，值还会带上引号。
        for param_name, param in sig.parameters.items():
            if param_name == 'self':
                continue

            # 获取类型
            param_type_hint = type_hints.get(param_name, str)
            param_type = self._python_type_to_tool_type(param_type_hint)

            # 判断是否必需
            # [机制] inspect.Parameter.empty 是一个哨兵值，专门表示「这个参数没有默认值」。
            # [易错] 不能用 param.default is None 来判断 —— 因为默认值本身完全可能就是 None。
            #        这里用 == 而不是 is：功能上等价，但读的时候容易误以为是 bug。
            required = param.default == inspect.Parameter.empty
            default = None if required else param.default

            # 获取描述
            description = param_descriptions.get(param_name, f"参数 {param_name}")

            parameters.append(ToolParameter(
                name=param_name,
                type=param_type,
                description=description,
                required=required,
                default=default
            ))

        return parameters

    # [作用] 从 docstring 的 Args: 段落里抠出「参数名 → 说明」。
    # [概念] 这是纯文本解析、靠正则，而不是靠 AST —— 所以格式稍微变一下就可能解析不到。
    # [为什么] 一旦解析失败，参数说明就退化成「参数 xxx」，模型看不到用途就会乱填值。
    #        这种「注释格式直接决定运行效果」正是工具系统最脆的地方。
    def _parse_param_descriptions(self, docstring: str) -> Dict[str, str]:
        """从 docstring 解析参数描述

        支持格式:
            Args:
                param_name: 参数描述
                another_param: 另一个参数描述
        """
        descriptions = {}

        # 查找 Args: 部分
        # [概念] re.search = 在整个字符串里找第一处匹配（对比 re.match 只从开头找）。
        # [语法] 逐段拆这条模式：
        #        Args:\s*\n              —— 先找到 "Args:" 以及它后面的空白和换行
        #        (.*?)                   —— 捕获组，非贪婪：尽量少地吃字符
        #        (?:\n\s*\n|Returns:|$)  —— 遇到空行 / "Returns:" / 字符串结尾就停
        #        re.DOTALL               —— 让 . 也能匹配换行符（默认不匹配），否则跨行匹配必然失败。
        args_match = re.search(r'Args:\s*\n(.*?)(?:\n\s*\n|Returns:|$)', docstring, re.DOTALL)
        if not args_match:
            return descriptions

        args_section = args_match.group(1)

        # 解析每个参数
        # 匹配格式: param_name: 描述 或 param_name (type): 描述
        # [语法] 这条模式里有 4 个新东西：
        #        (?:...)       非捕获组，只分组、不占编号；
        #        [^)]+         不含右括号的一段，用来吃掉 "(str)" 这种类型标注；
        #        (?=...)       前瞻断言：只要求「后面是某个东西」，但不把它吃进结果；
        #        re.MULTILINE  让 ^ / $ 按每一行算，而不是整段文字的首尾。
        param_pattern = r'^\s*(\w+)(?:\s*\([^)]+\))?\s*:\s*(.+?)(?=^\s*\w+\s*(?:\([^)]+\))?\s*:|$)'
        matches = re.finditer(param_pattern, args_section, re.MULTILINE | re.DOTALL)

        for match in matches:
            param_name = match.group(1).strip()
            param_desc = match.group(2).strip()
            # 清理描述中的多余空白
            # [机制] 把描述里的连续空白（含换行）压成一个空格 —— 因为这段文字最终要拼进提示词，
            #        换行多了会让提示词的结构变乱。
            param_desc = re.sub(r'\s+', ' ', param_desc)
            descriptions[param_name] = param_desc

        return descriptions

    # [作用] 「Python 类型对象 → JSON Schema 类型字符串」的查找表。
    # [概念] 类型注解在运行时其实是**对象**（str 是类对象，list[int] 是 GenericAlias），
    #        所以能像普通值一样比较、放进字典当键。
    # [易错] 兜底是 "string"：表里没有的类型（自定义类、tuple、Optional[int]……）
    #        一律被当成字符串，不报错也不提示。静默降级是最难查的那类问题。
    def _python_type_to_tool_type(self, py_type) -> str:
        """将 Python 类型转换为工具类型字符串"""
        # 处理泛型类型
        # [机制] list[int] 这类泛型类型本身不是 list，它的 __origin__ 才是 list。
        #        所以要先取 origin 再判断，才能认出「带元素的列表」。
        origin = getattr(py_type, '__origin__', None)
        if origin is not None:
            if origin is list:
                return "array"
            elif origin is dict:
                return "object"

        # 处理基本类型
        type_map = {
            str: "string",
            int: "integer",
            float: "number",
            bool: "boolean",
            list: "array",
            dict: "object",
        }

        return type_map.get(py_type, "string")

    # [作用] 实现 Tool 的抽象方法 —— 把构造时解析好的结果交出去。
    # [概念] 这一步是「还债」：Tool 里声明的是抽象方法，子类必须给出实现，
    #        否则造实例时会直接抛 TypeError（抽象基类的账本机制见 core/agent.py）。
    def get_parameters(self) -> List[ToolParameter]:
        """获取参数列表"""
        return self._parameters

    # [作用] 实现 Tool 的第二个抽象方法：把参数字典原样摊开，调用父工具上的那个方法。
    # [机制] self.method(**parameters) 里的 ** 是「把字典解包成关键字参数」：
    #        {"content": "x"} 会变成 method(content="x")。
    # [易错] 正因为用的是 ** 解包，参数字典的键必须和方法的形参名**严格一致**。
    #        这也是 registry 里那句 tool.run({"input": ...}) 要求方法参数名叫 input 的根本原因。
    # [易错] 方法抛异常时这里不兜底，会直接冒泡给调用方（registry.execute_tool 才用 try 接住）。
    def run(self, parameters: Dict[str, Any]) -> str:
        """执行方法"""
        return self.method(**parameters)
