# ===== 文件导读 =====
# [职责] 把多个工具按固定顺序串起来：上一步的输出，变成下一步的输入。
# [位置] tools/ 包里的另一个旁支 —— 和 async_executor 一样，没有任何 Agent 调用它，
#        只在 tools/__init__.py 的导出列表里出现。Agent 想串工具，走的是 ReAct 那种「模型自己决定下一步」。
# [阅读顺序] ① ToolChain.__init__ / add_step（链长什么样：只是一张「步骤表」）
#            → ② execute（唯一的执行入口，重点看第 65 行的模板替换和第 75 行的死代码）
#            → ③ ToolChainManager（给链再套一层管理器）
#            → ④ 两个 create_* 便捷函数（重点：它们引用的工具名根本不存在）。
# [本文件新概念] ① 模板字符串与 str.format 变量替换　② 链式编排（数据在步骤间流动）
#                ③ 组合：链只存「说明」，不存工具本体　④ or 短路做默认值　⑤ 异常边界该画在哪。
# [实测] 两个便捷函数造出来的链，跑起来一定失败但日志全绿 —— 见 create_research_chain 的注释。
# ===================
"""工具链管理器 - HelloAgents工具链式调用支持"""

# [语法] 只导入「类型注解用的工具」，运行时几乎不参与逻辑；真正干活的依赖只有下面那一个。
from typing import List, Dict, Any, Optional
# [语法] 相对导入指向同目录的 registry.py —— 链自己不认识工具怎么实现，只认识注册表的 execute_tool()。
# [概念] 这是很干净的分层：chain 依赖 registry，registry 依赖 base，没有反向依赖。
from .registry import ToolRegistry


# [作用] 「一张步骤表」+ 「照着表跑一遍」的执行器。
# [概念] 组合而非继承：ToolChain 不是工具，它**持有**一串步骤说明，执行时才去 registry 里取工具。
# [为什么] 这样链可以被定义、被打印、被存起来，而不必立刻绑定到某个注册表上 ——
#        注意下面 add_step 时根本不需要 registry，直到 execute 才传进来。
class ToolChain:
    """工具链 - 支持多个工具的顺序执行"""

    # [作用] 只存名字、描述和一张空步骤表 —— 还没有任何工具被牵扯进来。
    # [语法] List[Dict[str, Any]] 是「字典组成的列表」：每个字典描述一个步骤。
    # [易错] 这里的 [] 写在 __init__ 里，所以每条链各有各的步骤表；
    #        若写成类属性 steps = []，所有 ToolChain 实例会共用同一个列表（可变默认值陷阱的同类）。
    def __init__(self, name: str, description: str):
        self.name = name
        self.description = description
        self.steps: List[Dict[str, Any]] = []

    # [作用] 往步骤表尾部加一条。注意它**不检查工具是否存在** —— 名字写错了要等执行时才暴露。
    # [参数] input_template 是本文件的灵魂：一个带占位符的字符串，执行时才把变量填进去。
    # [易错] 只有字面量字符串才叫模板。写 "2 + 2" 这种没有占位符的，就是写死的常量，
    #        上一步的结果根本传不进来（create_research_chain 就犯了这个错）。
    def add_step(self, tool_name: str, input_template: str, output_key: str = None):
        """
        添加工具执行步骤
        
        Args:
            tool_name: 工具名称
            input_template: 输入模板，支持变量替换，如 "{input}" 或 "{search_result}"
            output_key: 输出结果的键名，用于后续步骤引用
        """
        # [概念] 一个步骤就是一个普通字典，三个键：跑哪个工具、传什么、结果存哪。
        #        用字典而不是定义一个小类：步骤是纯数据，没有行为，字典更轻。
        step = {
            "tool_name": tool_name,
            "input_template": input_template,
            # [语法] or 短路做默认值：output_key 是真值就用它，是 None 才用右边的。
            # [易错] 这里用的 len(self.steps) 是**追加之前**的长度，所以第一步的默认键是 step_0_result，
            #        和日志里打印的「步骤 1」差一位。默认键是 0 基的，别按 1 基去引用。
            "output_key": output_key or f"step_{len(self.steps)}_result"
        }
        self.steps.append(step)
        # [易错] 这条日志说「添加成功」，但它其实没验证任何东西：工具是否存在、模板变量是否拼得出来，
        #        这里一概不查。绿色的 ✅ 给了虚假的安全感。
        print(f"✅ 工具链 '{self.name}' 添加步骤: {tool_name}")

    # [作用] 照着步骤表跑一遍，返回最后一步的结果。
    # [参数] registry 在执行时才传进来（解耦）；input_data 是链的初始输入；
    #        context 是变量池，外部可以预置一些值给模板用。
    # [返回] 最后一步的输出字符串。注意**中途失败也是返回字符串**，不抛异常。
    # [易错] 参数默认值写 None 而不是 {} —— 这是对的！若写 context: Dict = {}，
    #        所有调用会共享同一个字典，前一次执行留下的变量会污染后一次。
    def execute(self, registry: ToolRegistry, input_data: str, context: Dict[str, Any] = None) -> str:
        """
        执行工具链
        
        Args:
            registry: 工具注册表
            input_data: 初始输入数据
            context: 执行上下文，用于变量替换
            
        Returns:
            最终执行结果
        """
        # [机制] 空链直接返回错误字符串。这是本文件里少数几个「自己先挡一道」的地方。
        if not self.steps:
            return "❌ 工具链为空，无法执行"

        print(f"🚀 开始执行工具链: {self.name}")
        
        # 初始化上下文
        if context is None:
            context = {}
        # [机制] 把初始输入塞进变量池，键名固定叫 input —— 于是模板里写 {input} 就能拿到它。
        # [易错] 这是**直接改传进来的那个字典**（不是拷贝）。调用方如果复用同一个 context，
        #        上一次执行留下的 step_N_result 会留在里面，下一次可能被模板意外取到。
        context["input"] = input_data
        
        # [机制] 先兜个底：万一链里一个能跑的步骤都没有（全被 continue 跳过了），至少返回原始输入。
        final_result = input_data
        
        # [语法] enumerate 同时给出下标 i 和元素 step；i 从 0 开始，日志里用 i+1 显示成「第几步」。
        # [概念] 这就是「链」的全部实现 —— 一个顺序 for 循环。
        #        没有分支、没有重试、没有「下一步该干嘛看情况」：顺序在 add_step 时就定死了。
        # [为什么] 正因如此，它只适合「步骤事先确定」的任务；
        #        需要「看结果再决定下一步」的场景，得用 ReAct 那种由模型临场决策的范式。
        for i, step in enumerate(self.steps):
            tool_name = step["tool_name"]
            input_template = step["input_template"]
            output_key = step["output_key"]
            
            print(f"📝 执行步骤 {i+1}/{len(self.steps)}: {tool_name}")
            
            # 替换模板中的变量
            # [概念] ★ 这是链式调用的数据流枢纽：把变量池里的值填进模板，拼出这一步真正的输入。
            # [语法] **context 是「字典解包成关键字参数」—— 和之前 AutoGeneratedTool.run 里那个 ** 是同一个语法。
            #        模板 {input} 正好对上 context["input"]，靠的是「键名 == 占位符名」。
            try:
                # [机制] str.format 会扫描模板里的 {}，用关键字参数逐个替换。
                #        上一步的结果之所以能流到这一步，就是因为前面执行完把它写进了 context[output_key]，
                #        而这一步的模板里写了对应的 {output_key}。
                actual_input = input_template.format(**context)
            # [易错] 只捕获了 KeyError，而 format 的失败方式不止这一种。实测：
            #        "{nope}"      → KeyError: 'nope'        ← 被这里接住，返回友好提示
            #        '{"a": 1}'    → KeyError: '"a"'        ← 也接住（JSON 字面量会被当成占位符）
            #        "{}"          → IndexError              ← 接不住，整条链当场炸穿
            #        所以「模板写错」这件事，有时变成一句友好提示，有时直接把程序掀翻。
            except KeyError as e:
                return f"❌ 模板变量替换失败: {e}"
            
            # 执行工具
            # [概念] 这里想表达的意图是「单步失败就中止整条链」，思路是对的。
            try:
                # [机制] 真正的调用只有这一行 —— 链不直接碰工具，一律通过注册表。
                # [易错] ★ 但 execute_tool **从不抛异常**：它内部把一切错误都转成了字符串返回。
                #        所以工具报错时这里拿到的是一个正常字符串，会一路当成「成功结果」走下去。
                result = registry.execute_tool(tool_name, actual_input)
                context[output_key] = result
                final_result = result
                print(f"✅ 步骤 {i+1} 完成")
            # [易错] ★ 这段是死代码。实测：故意把第 2 步写成一个不存在的工具名，运行输出是
            #            📝 执行步骤 2/2: 不存在的工具
            #            ✅ 步骤 2 完成          ← 绿的
            #            🎉 工具链 't' 执行完成
            #        返回的却是「错误：未找到名为 '不存在的工具' 的工具。」——
            #        except 分支一次都没进过，因为上游根本不抛。
            # [为什么] 这就是「错误也是上下文」那个设计（registry 里刻意选的）在链上的副作用：
            #        单个工具调用时它是优点，串成链之后它把这个 except 架空了。
            # [易错] 更隐蔽的后果：context[output_key] 被设成了那句错误文字，
            #        下一步的模板会把它当正常数据插进去，错误就这么悄悄地往下游传播。
            except Exception as e:
                return f"❌ 工具 '{tool_name}' 执行失败: {e}"
        
        # [易错] 只要没在半路 return，这里就一定会打印「执行完成」—— 哪怕每一步拿到的都是错误字符串。
        #        日志的「成功」和实际的成功之间没有必然联系。
        print(f"🎉 工具链 '{self.name}' 执行完成")
        return final_result


# [作用] 给一堆链再套一层管理器：按名字存取、按名字执行。
# [概念] 这个类的结构和 registry 几乎一样（一个字典 + register / execute / list），
#        它是「注册表」这个模式在「链」这一层的复刻。
# [实测] 全仓库没有任何一处使用它，也没有任何 Agent 引用过 ToolChain。
class ToolChainManager:
    """工具链管理器"""

    # [作用] 绑定一个注册表（链执行时要用），再建一张「链名 → 链」的表。
    # [易错] 所有链共用这一个 registry，所以链里若引用了别的链才有的工具，
    #        只要在同一个 registry 里就照样能跑 —— 隔离完全靠命名自觉。
    def __init__(self, registry: ToolRegistry):
        self.registry = registry
        self.chains: Dict[str, ToolChain] = {}

    # [作用] 按 chain.name 存进去。
    # [易错] 和 registry.register_tool 一样是覆盖式的：重名不报错、直接顶掉，
    #        但这里连一句覆盖警告都没打 —— 静默替换比 registry 那边更隐蔽。
    def register_chain(self, chain: ToolChain):
        """注册工具链"""
        self.chains[chain.name] = chain
        print(f"✅ 工具链 '{chain.name}' 已注册")

    # [作用] 按名字找链并执行。链不存在时返回错误字符串（和 registry 的风格一致）。
    # [概念] 这里是委托：管理器自己不算，活全部交给 ToolChain.execute。
    def execute_chain(self, chain_name: str, input_data: str, context: Dict[str, Any] = None) -> str:
        """执行指定的工具链"""
        if chain_name not in self.chains:
            return f"❌ 工具链 '{chain_name}' 不存在"

        chain = self.chains[chain_name]
        return chain.execute(self.registry, input_data, context)

    def list_chains(self) -> List[str]:
        """列出所有已注册的工具链"""
        return list(self.chains.keys())

    # [作用] 把链的步骤表导出成普通字典（用于展示 / 调试 / 交给模型看）。
    # [语法] 返回值里 step_details 那一大坨是列表推导式 + 字典字面量，
    #        整体意思就是「把每个步骤字典挑三个键、重组成新字典」。
    # [易错] 它返回的是**新建的字典**，改它不会影响链本身 —— 和 registry.list_tools() 一样是防御性拷贝。
    def get_chain_info(self, chain_name: str) -> Optional[Dict[str, Any]]:
        """获取工具链信息"""
        if chain_name not in self.chains:
            return None
        
        chain = self.chains[chain_name]
        return {
            "name": chain.name,
            "description": chain.description,
            "steps": len(chain.steps),
            "step_details": [
                {
                    "tool_name": step["tool_name"],
                    "input_template": step["input_template"],
                    "output_key": step["output_key"]
                }
                for step in chain.steps
            ]
        }


# 便捷函数
# [作用] 预置一条「研究链」：搜索 → 计算。
# [易错] ★ 它的 docstring 写着「搜索 -> 计算 -> 总结」，实际只有两步，没有总结。
# [实测] 第 1 步的工具名 'search' 是对的（SearchTool 注册名实测就是 search），
#        但第 2 步的 'my_calculator' 不存在 —— CalculatorTool 注册名实测是 'python_calculator'。
#        所以这条链跑起来必然在第 2 步失败，而日志照样全绿（原因见 execute 里的死代码注释）。
def create_research_chain() -> ToolChain:
    """创建一个研究工具链：搜索 -> 计算 -> 总结"""
    chain = ToolChain(
        name="research_and_calculate",
        description="搜索信息并进行相关计算"
    )

    # 步骤1：搜索信息
    chain.add_step(
        tool_name="search",
        input_template="{input}",
        output_key="search_result"
    )

    # 步骤2：基于搜索结果进行计算
    # [易错] ★ 这是本文件最典型的一处「假装在串链」：
    #        docstring 说「基于搜索结果进行计算」，而 input_template 写的是常量 "2 + 2" ——
    #        第 1 步辛苦搜出来的 search_result 压根没被用到，两步之间没有任何数据流动。
    # [概念] 判断一条链是不是真的链，只看一件事：**后一步的模板里有没有前一步的 output_key**。
    #        正确写法应该是 input_template="{search_result}" 之类。
    chain.add_step(
        tool_name="my_calculator",
        input_template="2 + 2",  # 简单的计算示例
        output_key="calc_result"
    )

    return chain


# [作用] 最小示例：一条只有一个计算步骤的链。
# [实测] 它引用的 'my_calculator' 同样不存在，所以 execute 的结果是
#        「错误：未找到名为 'my_calculator' 的工具。」—— 但终端上打的是 ✅ 和 🎉。
# [为什么] 一个只有一步的「链」其实没有任何链的意义；
#        真正体现链价值的，是第 2 步的模板里写 {第1步的 output_key}。
def create_simple_chain() -> ToolChain:
    """创建一个简单的工具链示例"""
    chain = ToolChain(
        name="simple_demo",
        description="简单的工具链演示"
    )

    # 只包含一个计算步骤
    chain.add_step(
        tool_name="my_calculator",
        input_template="{input}",
        output_key="result"
    )

    return chain
