"""第 2 组：工具系统（tools/base.py · tools/registry.py）。

不需要 API Key —— 这一组只验证「工具怎么定义、怎么注册、怎么展开、怎么被调用」。
前几轮实测发现的坑，在这里全部变成可复跑的断言。
"""
import pathlib
import sys
from typing import Any, Dict, List

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))

from checks import Check, expect_raise, quiet


# ══════════════════════════════════════════════════════════════
# 被测样板工具：一个「可展开」的工具，父工具是外壳，功能挂在 @tool_action 方法上
# ══════════════════════════════════════════════════════════════
def build_text_tool():
    from hello_agents.tools.base import Tool, ToolParameter, tool_action

    class TextTool(Tool):
        def __init__(self):
            super().__init__(name="text", description="文本工具箱", expandable=True)

        def run(self, parameters: Dict[str, Any]) -> str:
            return "请调用展开后的子工具"

        def get_parameters(self) -> List[ToolParameter]:
            return []

        @tool_action("text_char_count", "统计文本的字符数")
        def _char_count(self, input: str) -> str:
            # ⚠ 参数名必须叫 input —— 见下面 C 组的原因
            return f"{len(input)} 个字符"

        @tool_action("text_upper", "把文本转成大写")
        def _upper(self, input: str) -> str:
            return input.upper()

        @tool_action("text_wrong_param", "参数名故意写错，用来验证约定")
        def _wrong(self, text: str) -> str:
            return text

    return TextTool


def run(c: Check) -> None:
    from hello_agents.tools.base import Tool, ToolParameter, tool_action
    from hello_agents.tools.registry import ToolRegistry

    # ────────────────────────────────────────────────────────────
    c.section("A. Tool 契约（tools/base.py）")

    c.ok(issubclass(Tool, object), "Tool 存在且是可继承的基类")
    err = expect_raise(TypeError, Tool, "x", "y")
    c.ok(
        err is not None and not isinstance(err, tuple),
        "Tool 是抽象类：Tool('x','y') 直接实例化会抛 TypeError",
        f"实际得到 {err!r}",
    )
    c.ok(
        {"run", "get_parameters"} <= set(Tool.__abstractmethods__),
        "账本里同时记着 run 和 get_parameters（两个都必须实现）",
        f"实际账本：{Tool.__abstractmethods__}",
    )

    tag = getattr(tool_action, "__name__", "")
    c.eq(tag, "tool_action", "tool_action 是一个装饰器工厂（调用它返回真正的 decorator）")

    TextTool = build_text_tool()
    t = TextTool()
    c.ok(t.expandable, "expandable=True 表示这个工具会展开成多个子工具")

    with quiet():
        children = t.get_expanded_tools()
    names = sorted(x.name for x in children)
    c.eq(names, ["text_char_count", "text_upper", "text_wrong_param"],
          "机制验证：get_expanded_tools 用 inspect 扫描出所有带 @tool_action 标记的方法")

    # ────────────────────────────────────────────────────────────
    c.section("B. ToolRegistry —— 注册、展开、执行（tools/registry.py）")

    with quiet():
        reg = ToolRegistry()
        reg.register_tool(TextTool(), auto_expand=True)
    listed = sorted(reg.list_tools())
    c.eq(listed, ["text_char_count", "text_upper", "text_wrong_param"],
          "注册一个可展开工具 → 注册表里出现 3 个独立子工具（而不是父工具 'text'）")

    desc = reg.get_tools_description()
    c.ok("text_char_count" in desc and "统计文本的字符数" in desc,
          "get_tools_description() 输出「工具名: 描述」—— 这就是喂给模型的提示词内容")

    # ⚠ 这张说明里【没有参数名】—— 而 SimpleAgent 的提示词却要求「参数名必须完全匹配」
    lines = desc.splitlines()
    c.ok("input" not in desc,
         "⚠ 机制缺陷：工具说明里不含参数名（模型无从知道该写哪个 key，只能猜）",
         f"实际说明：{desc!r}")
    c.ok(len(lines) == 3 and all(l.startswith("- ") and ": " in l for l in lines),
         "每行格式固定为「- 工具名: 描述」，没有任何结构化参数信息（类型/必填都没给）",
         f"实际 {len(lines)} 行：{lines!r}")
    c.known_defect(
        "get_tools_description() 只输出「- 工具名: 描述」，不含参数名",
        "但 SimpleAgent 的系统提示词写着「参数名必须与工具定义的参数名完全匹配」——"
        "模型无从知道参数名，只能猜。猜成 text=/content=/query= 就会撞上 "
        "'unexpected keyword argument'。实测：本 demo 的 --live 第一次跑就因此失败",
    )

    with quiet():
        out = reg.execute_tool("text_char_count", "深度学习")
    c.ok("4" in out, "execute_tool('text_char_count', '深度学习') 返回了字符数 4", f"实际返回 {out!r}")

    with quiet():
        out2 = reg.execute_tool("text_upper", "abc")
    c.ok("ABC" in out2, "同一个工具的另一个 action 也能被调用（展开后可独立寻址）", f"实际返回 {out2!r}")

    # ────────────────────────────────────────────────────────────
    c.section("C. ⚠ 参数名约定：为什么 @tool_action 方法的参数必须叫 input")

    # 机制：ToolRegistry.execute_tool 固定传 {"input": 传入的字符串}
    #      而 AutoGeneratedTool.run 是 self.method(**parameters)
    with quiet():
        ok_out = reg.execute_tool("text_char_count", "abc")
    c.ok("3" in ok_out, "参数名叫 input 的方法：纯文本调用能正常工作")

    with quiet():
        bad_out = reg.execute_tool("text_wrong_param", "abc")
    c.ok(
        "错误" in bad_out or "异常" in bad_out,
        "参数名叫 text 的方法：同样调用会失败（这就是「参数名必须叫 input」的证据）",
        f"实际返回 {bad_out!r}",
    )
    c.known_defect(
        "AutoGeneratedTool.run 是 self.method(**parameters)，而注册表固定传 {'input': ...}",
        "结果：@tool_action 方法只要形参不叫 input，纯文本调用就必然报 "
        "'unexpected keyword argument'。内置 22 个 @tool_action 方法没有一个叫 input，"
        "它们只能靠模型写 key=value 才能工作",
    )

    # ────────────────────────────────────────────────────────────
    c.section("D. 两种注册方式的行为差异（register_function vs register_tool）")

    with quiet():
        reg2 = ToolRegistry()
        reg2.register_function("now", "返回一个固定时间", lambda text: "2026-01-01")

    c.ok("now" in reg2.get_tools_description(), "函数式工具会出现在「工具说明」里（模型看得见）")
    with quiet():
        r = reg2.execute_tool("now", "随便")
    c.ok("2026" in r, "registry.execute_tool 能调用函数式工具")
    c.ok(reg2.get_tool("now") is None, "但 get_tool('now') 返回 None —— 它不在 Tool 对象表里")

    from hello_agents.agents.simple_agent import SimpleAgent
    from fake_llm import FakeLLM

    agent = SimpleAgent(name="探针", llm=FakeLLM(replies=["测试"]), tool_registry=reg2)
    with quiet():
        agent_result = agent._execute_tool_call("now", "随便")
    c.ok(
        "未找到工具" in agent_result,
        "⚠ SimpleAgent._execute_tool_call 找不到函数式工具（它只查 get_tool）",
        f"实际返回 {agent_result!r}",
    )
    c.known_defect(
        "SimpleAgent 只认 Tool 对象，不认 register_function 注册的函数工具",
        "而 get_tools_description() 又会把函数式工具列进提示词 —— "
        "模型被告知有一个它根本调不动的工具（实测会回答「未找到工具」）",
    )

    # ────────────────────────────────────────────────────────────
    c.section("E. 内置工具 calculator 的当前状态（tools/builtin/calculator.py）")

    from hello_agents.tools.builtin.calculator import CalculatorTool

    with quiet():
        calc = CalculatorTool()
        calc_out = calc.run({"input": "1+1"})
    if "2" in calc_out and "失败" not in calc_out:
        c.ok(True, "calculator 能正常计算 1+1")
    else:
        c.ok(
            "Num" in calc_out or "失败" in calc_out or "错误" in calc_out,
            "calculator 确实无法计算（返回了失败信息，而不是悄悄给错答案）",
            f"实际返回 {calc_out!r}",
        )
        c.known_defect(
            "CalculatorTool 在 Python 3.12+ 上完全不可用",
            "原因：tools/builtin/calculator.py 里有 `isinstance(node, ast.Num)` 分支，"
            "而 ast.Num 在 Python 3.12 已被移除 —— 访问该属性即抛 "
            "AttributeError: module 'ast' has no attribute 'Num'",
        )

    # ────────────────────────────────────────────────────────────
    c.section("F. 工具参数类型名：全称 vs 缩写")

    p_int = ToolParameter(name="n", type="integer", description="整数")
    p_abbr = ToolParameter(name="n", type="int", description="缩写写法的整数")
    c.eq(p_int.type, "integer", "ToolParameter 接受 'integer'")
    c.eq(p_abbr.type, "int", "ToolParameter 也接受 'int'（但下面会看到它翻译不出来）")
